### ISSUE TITLE
您好，请问报了这个错误是什么情况

### ISSUE THREAD

**Issue by gchonpo** [walking-shadow/Semantic-guidance-and-spatial-localization-network#1]
Traceback (most recent call last):
  File "/home/cwb/code/Semantic-guidance-and-spatial-localization-network-main/train.py", line 213, in <module>
    auto_experiment()
  File "/home/cwb/code/Semantic-guidance-and-spatial-localization-network-main/train.py", line 60, in auto_experiment
    train_net(dataset_name=ph.dataset_name)
  File "/home/cwb/code/Semantic-guidance-and-spatial-localization-network-main/train.py", line 106, in train_net
    train_loader = DataLoaderX(train_dataset, shuffle=True, drop_last=False, batch_size=ph.batch_size, **loader_args)
TypeError: __init__() got an unexpected keyword argument 'pin_memeory'

运行后报了这个错，数据集用的LEVIR-CD，pytorch版本用的1.12的

**Comment by walking-shadow** [comment]
库的版本问题，不想调整库的版本的话，直接把loader_args里面的pin_memeory参数删除即可

**Comment by gchonpo** [comment]
谢谢您的回答，请问能提供一份最新的requirement吗，因为里面版本导致的问题有挺多的

**Comment by walking-shadow** [comment]
已设置prefetch_generator的特定版本，另外两个没有设置版本的onnx和netron只是为了可视化，训练和测试过程中不需要用到

**Comment by walking-shadow** [comment]
我将关闭这个issue
